# Cache maven cache directory so external artifacts dont need to be
# re-downloaded.
cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

env:
  global:
    - DEPLOY=1

notifications:
  email: false

install: /bin/true

script: mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar -Dsonar.projectKey=openstack4j_openstack4j

after_success:
  - "[[ $DEPLOY == 1 && $TRAVIS_BRANCH == \"master\" ]] && { mvn deploy --settings distribution/settings.xml -DskipTests=true -B; };"

# disable sudo to ensure that this build runs on the travis container-based
# infrastructure. This should prevent the buffer overflow from
# https://github.com/travis-ci/travis-ci/issues/5227
sudo: false

# due to travis-ci changes in default build environment,
# this must be specify in order for oraclejdk8 to install
# https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
dist: trusty

addons:
  sonarcloud: # Report coverage results to sonarcloud.io
    organization: "openstack4j"
    token:
      secure: "S9xKYmp0TYrzEozGaNqYE3e6hSBV3nDnA1oy3V5vWXW8U1EYFy/kkQbkqN4s6xDkM0nWbbHm23INkTOrhl8clUxBeWt7Mt1PKeH45PgkCbS0oZoIvSlmASKxXsKkK34MniF6yOsn4+Z0iqAr4E2sdxcPmP1mT4I2pQJs4eRpmUy7SfUomBjd1TcV/r2DKlh6SUspJEi6NwnSdGr41gw1vbjtgTJBUmsvw9N04VCH1if8vgxrZGfkV1EjqJ3/SS7C+lLfdJQgUp4JFKrEoBU6RIwwBciKfW/3+jDuR5Lk6FbpSe4Vv98iGBw4NP079InLu6asglY2nEt8U9WC9BoTyVqCdCooz4j8b/FNyXU9cYEnNlOvtJ7vM9/BxZOqUplR4xpb9oMLLkWeT8N5OJCnCOyrk4myRSXEhLyX4SOj3gT+uxWhdBBbyH3XGrFMVci1WOe7upKUpM2MRsk7Ura0Xf7keiC13DFHdT3Hm+vIyEnzClk48TzIyvNVLuOBoBn5Ka0S5yBD8MKp0/FmoK1kuNtEhI5a877R/PF3ZxY2OxLyrUrAu0SL1Ncaz9Gyekcqa8V5yOVTyKF/fUErqd51u58Me23U1Hu2qjKk/TK3fFcK9Y8byvVqUGoVyLhW3uc3idPhCDiC6RvLn+FIsQ0rg5zOGMVJ4nDKw40UQ22ar78="
